"""Stable reason codes for the TGTC qualification pipeline.

Reason codes are intentionally strings at the persistence boundary.  The enum
prevents spelling drift inside Python while ``coerce_reason`` preserves forward
compatibility with historical artifacts that may contain older codes.
"""

from __future__ import annotations

from enum import Enum


class ReasonCode(str, Enum):
    # Positive / routing outcomes
    FINAL_PASS = "FINAL_PASS"
    NEEDS_CHECK_ATS_TEMPORARILY_UNAVAILABLE = "NEEDS_CHECK_ATS_TEMPORARILY_UNAVAILABLE"
    NEEDS_CHECK_NONSTANDARD_CONTACT_TITLE = "NEEDS_CHECK_NONSTANDARD_CONTACT_TITLE"
    NEEDS_CHECK_MINOR_NONCRITICAL_DISCREPANCY = "NEEDS_CHECK_MINOR_NONCRITICAL_DISCREPANCY"
    REROUTE_FUNCTION_MISMATCH = "REROUTE_FUNCTION_MISMATCH"
    REROUTE_SENIORITY_MISMATCH = "REROUTE_SENIORITY_MISMATCH"
    REROUTE_TERRITORY_MISMATCH = "REROUTE_TERRITORY_MISMATCH"
    REROUTE_NOT_CURRENT_EMPLOYEE = "REROUTE_NOT_CURRENT_EMPLOYEE"
    REROUTE_WRONG_ORGANIZATION = "REROUTE_WRONG_ORGANIZATION"
    REROUTE_EMAIL_IDENTITY_MISMATCH = "REROUTE_EMAIL_IDENTITY_MISMATCH"

    # Job source / integrity
    REJECT_JOB_INACTIVE = "REJECT_JOB_INACTIVE"
    REJECT_UNRESOLVABLE_POSTING = "REJECT_UNRESOLVABLE_POSTING"
    REJECT_MULTI_JOB_ROUNDUP = "REJECT_MULTI_JOB_ROUNDUP"
    REJECT_EMPLOYER_POSTING_MISMATCH = "REJECT_EMPLOYER_POSTING_MISMATCH"
    REJECT_MALFORMED_TITLE = "REJECT_MALFORMED_TITLE"
    UNVERIFIED_OFFICIAL_SOURCE = "UNVERIFIED_OFFICIAL_SOURCE"
    UNVERIFIED_SOURCE_TIMEOUT = "UNVERIFIED_SOURCE_TIMEOUT"
    UNVERIFIED_SOURCE_CONFLICT = "UNVERIFIED_SOURCE_CONFLICT"
    UNVERIFIED_JOB_STATUS = "UNVERIFIED_JOB_STATUS"
    TITLE_NORMALIZED_NONMATERIAL = "TITLE_NORMALIZED_NONMATERIAL"
    TITLE_MATERIAL_MISMATCH = "TITLE_MATERIAL_MISMATCH"
    TITLE_SENIORITY_MISMATCH = "TITLE_SENIORITY_MISMATCH"
    TITLE_FUNCTION_MISMATCH = "TITLE_FUNCTION_MISMATCH"

    # Employment / arrangement / geography
    REJECT_NON_US_SCOPE = "REJECT_NON_US_SCOPE"
    REJECT_FOREIGN_ONLY_SCOPE = "REJECT_FOREIGN_ONLY_SCOPE"
    REJECT_LOCAL_RESIDENCY_REQUIRED = "REJECT_LOCAL_RESIDENCY_REQUIRED"
    REJECT_ONSITE_REQUIRED = "REJECT_ONSITE_REQUIRED"
    REJECT_HYBRID_REQUIRED = "REJECT_HYBRID_REQUIRED"
    REJECT_LOCAL_PRESENCE_REQUIRED = "REJECT_LOCAL_PRESENCE_REQUIRED"
    REJECT_FIELD_WORK_REQUIRED = "REJECT_FIELD_WORK_REQUIRED"
    REJECT_TRAVEL_REQUIRED = "REJECT_TRAVEL_REQUIRED"
    REJECT_RELOCATION_REQUIRED = "REJECT_RELOCATION_REQUIRED"
    REJECT_PART_TIME = "REJECT_PART_TIME"
    REJECT_CONTRACT = "REJECT_CONTRACT"
    REJECT_FIXED_TERM = "REJECT_FIXED_TERM"
    REJECT_FRACTIONAL = "REJECT_FRACTIONAL"
    REJECT_TEMPORARY = "REJECT_TEMPORARY"
    REJECT_FREELANCE = "REJECT_FREELANCE"
    REJECT_SEASONAL = "REJECT_SEASONAL"
    REJECT_INTERNSHIP = "REJECT_INTERNSHIP"
    REJECT_NON_PAYING = "REJECT_NON_PAYING"
    REJECT_SECURITY_CLEARANCE_REQUIRED = "REJECT_SECURITY_CLEARANCE_REQUIRED"
    REJECT_MANDATORY_PROFESSIONAL_LICENSE = "REJECT_MANDATORY_PROFESSIONAL_LICENSE"
    REJECT_PHYSICAL_FACILITY_REQUIREMENT = "REJECT_PHYSICAL_FACILITY_REQUIREMENT"
    UNVERIFIED_EMPLOYMENT_TYPE = "UNVERIFIED_EMPLOYMENT_TYPE"
    UNVERIFIED_EMPLOYMENT_DURATION = "UNVERIFIED_EMPLOYMENT_DURATION"
    UNVERIFIED_WORK_ARRANGEMENT = "UNVERIFIED_WORK_ARRANGEMENT"
    UNVERIFIED_INTENT_MARKET = "UNVERIFIED_INTENT_MARKET"
    UNVERIFIED_GEOGRAPHIC_SCOPE = "UNVERIFIED_GEOGRAPHIC_SCOPE"

    # Account
    REJECT_COMPANY_TOO_SMALL = "REJECT_COMPANY_TOO_SMALL"
    REJECT_COMPANY_TOO_LARGE = "REJECT_COMPANY_TOO_LARGE"
    REJECT_EXCLUDED_INDUSTRY = "REJECT_EXCLUDED_INDUSTRY"
    REJECT_EXCLUDED_BUSINESS_MODEL = "REJECT_EXCLUDED_BUSINESS_MODEL"
    REJECT_STAFFING = "REJECT_STAFFING"
    REJECT_OUTSOURCING = "REJECT_OUTSOURCING"
    REJECT_GOVERNMENT = "REJECT_GOVERNMENT"
    REJECT_HEALTHCARE = "REJECT_HEALTHCARE"
    REJECT_CRM_EXISTING = "REJECT_CRM_EXISTING"
    REJECT_DUPLICATE_ACCOUNT = "REJECT_DUPLICATE_ACCOUNT"
    UNVERIFIED_ORGANIZATION = "UNVERIFIED_ORGANIZATION"
    UNVERIFIED_DOMAIN = "UNVERIFIED_DOMAIN"
    UNVERIFIED_EMPLOYEE_COUNT = "UNVERIFIED_EMPLOYEE_COUNT"
    UNVERIFIED_INDUSTRY = "UNVERIFIED_INDUSTRY"
    UNVERIFIED_BUSINESS_MODEL = "UNVERIFIED_BUSINESS_MODEL"
    UNVERIFIED_EMPLOYER_IDENTITY = "UNVERIFIED_EMPLOYER_IDENTITY"

    # Role
    REJECT_EXCLUDED_SENIORITY = "REJECT_EXCLUDED_SENIORITY"
    REJECT_ROLE_MISMATCH = "REJECT_ROLE_MISMATCH"
    REJECT_ROLE_NOT_SUPPORTED = "REJECT_ROLE_NOT_SUPPORTED"
    REJECT_ROLE_NOT_GLOBALLY_COVERABLE = "REJECT_ROLE_NOT_GLOBALLY_COVERABLE"
    REJECT_RESTRICTED_SPECIALIZATION = "REJECT_RESTRICTED_SPECIALIZATION"
    UNVERIFIED_ROLE_CLASSIFICATION = "UNVERIFIED_ROLE_CLASSIFICATION"

    # Contact / email
    UNVERIFIED_NO_VALID_CONTACT = "UNVERIFIED_NO_VALID_CONTACT"
    UNVERIFIED_CONTACT_EMPLOYMENT = "UNVERIFIED_CONTACT_EMPLOYMENT"
    REJECT_EMAIL_DOMAIN_MISMATCH = "REJECT_EMAIL_DOMAIN_MISMATCH"
    REJECT_EMAIL_IDENTITY_MISMATCH = "REJECT_EMAIL_IDENTITY_MISMATCH"
    UNVERIFIED_EMAIL = "UNVERIFIED_EMAIL"
    UNVERIFIED_EMAIL_DELIVERABILITY = "UNVERIFIED_EMAIL_DELIVERABILITY"

    # Orchestration
    TOPUP_DEFICIT_REMAINS = "TOPUP_DEFICIT_REMAINS"
    TARGET_REACHED = "TARGET_REACHED"
    API_BUDGET_EXHAUSTED = "API_BUDGET_EXHAUSTED"
    VALID_INVENTORY_EXHAUSTED = "VALID_INVENTORY_EXHAUSTED"
    EXTERNAL_DEPENDENCY_UNAVAILABLE = "EXTERNAL_DEPENDENCY_UNAVAILABLE"
    CIRCUIT_BREAKER_OPEN = "CIRCUIT_BREAKER_OPEN"
    RUNTIME_LIMIT_REACHED = "RUNTIME_LIMIT_REACHED"


def reason_value(value: ReasonCode | str | None) -> str:
    """Return a stable string without rejecting historical/experimental codes."""
    if isinstance(value, ReasonCode):
        return value.value
    return str(value or "").strip()
